<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Stash</RootNamespace>
    <DisableImplicitFSharpCoreReference>false</DisableImplicitFSharpCoreReference>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Types.fs" />
    <Compile Include="Tauri.fs" />
    <Compile Include="MainUI.fs" />
    <Compile Include="App.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Fable.Core" Version="4.*" />
    <PackageReference Include="Fable.Promise" Version="3.*" />
    <PackageReference Include="Fable.Browser.Dom" Version="2.*" />
    <PackageReference Include="Feliz" Version="2.*" />
  </ItemGroup>

</Project>
